[package]
name = "load_generator"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.x", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
rand = { version = "0.9.1", fefatures = ["full"] }